# server
server:
  #address: 127.0.0.1
  port: @server.port@
  servlet:
    context-path: /
    session:
      persistent: false

# spring
spring:
  # application
  application:
    name: @name@
    version: @version@
    url: @url@
    desc: @description@

  # datasource
  datasource:
    # 数据源名称
    name: master
    # 驱动
    driver-class-name: @datasource.master.driver-class-name@
    # url
    url: @datasource.master.url@
    # 用户名
    username: @datasource.master.username@
    # 密码
    password: @datasource.master.password@
    # 指定使用的数据源
    type: com.zaxxer.hikari.HikariDataSource
    # hikari
    hikari:
      # 池中最大连接数（包括空闲和正在使用的连接）
      maximum-pool-size: @datasource.master.maximum-pool-size@
      # 池中最小空闲连接数量
      minimum-idle: @datasource.master.minimum-idle@

  # jackson
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    custom-data-time-format: yyyy/MM/dd HH:mm:ss
    custom-date-format: yyyy/MM/dd
    custom-time-format: HH:mm:ss
    time-zone: GMT+8

  # 模板配置
  thymeleaf:
    # Thymeleaf的模板位置，默认值：classpath:/templates/
    prefix: classpath:/templates/
    # 匹配后缀
    suffix: .html
    # 模板模式
    mode1: HTML5
    # 模板编码
    encoding: UTF-8
    # 是否使用页面缓存
    cache: false

  # profiles
  profiles:
    active: @profiles.active@

# logging
logging:
  level:
    #root: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    # log
    # org.apache.ibatis.logging.nologging.NoLoggingImpl
    # org.apache.ibatis.logging.stdout.StdOutImpl
    # org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  # 全局配置
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
