server:
  servlet:
    session:
      # 设置会话过期时间：12h
      timeout: PT12H
      cookie:
        # 设置cookie过期时间：12h
        max-age: PT12H

spring:
  application:
    name: '@artifactId@'

  messages:
    basename: i18n/messages

  # 模板配置
  thymeleaf:
    # Thymeleaf的模板位置，默认值：classpath:/templates/
    prefix: classpath:/templates/
    # 匹配后缀
    suffix: .html
    # 模板模式
    mode1: HTML5
    # 模板编码
    encoding: UTF-8

  boot:
    admin:
      ui:
        title: 监控中心
        brand: '<img src="assets/img/icon-spring-boot-admin.svg"><span>监控中心</span>'
      probed-endpoints: '*'
      monitor:
        status-lifetime: 2000ms
        status-interval: 2000ms
        default-timeout: 2000ms
        default-retries: 0

  # 环境标识
  profiles:
    active: '@spring.profiles.active@'
