spring:
  application:
    name: '@artifactId@'
    version: '@version@'
    description: '@description@'

  # 当HTTP状态码为4xx时直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭默认的静态资源路径映射
      add-mappings: false

  profiles:
    active: '@spring.profiles.active@'

# mybatis-plus配置
mybatis-plus:
  configuration:
    # 开启驼峰配置
    map-underscore-to-camel-case: true

    # MyBatis自动映射策略：MyBatis在将数据库查询结果映射到Java对象时的自动映射策略
    # 在MyBatis中，有以下几种自动映射策略：
    # 1、NONE：不启用自动映射
    # 2、PARTIAL：只对非嵌套的 resultMap 进行自动映射
    # 3、FULL：对所有的 resultMap 都进行自动映射
    auto-mapping-behavior: full

    # 开启打印sql配置
    # 1、org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 2、org.apache.ibatis.logging.stdout.StdOutImpl
    # 3、org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml

  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1

# Actuator 配置
management:
  # 开启环境变量info信息配置
  info:
    env:
      enabled: true
  endpoints:
    # org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointProperties
    web:
      exposure:
        include: '*'
    # org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointProperties
    jmx:
      exposure:
        include: '*'
  endpoint:
    # 健康检测
    health:
      enabled: true
      show-details: always
    # 开启info端点
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true

  metrics:
    # 设置tag
    tags:
      application: ${spring.application.name}

