server:
  port: ${MONOLITHIC_WEB_PORT:8080}
  servlet:
    context-path: /
    session:
      persistent: false

spring:
  # Spring Boot Admin 配置
  boot:
    admin:
      # 密钥
      secret: kiiI6IkphFra!NUB4iLCJpYXQN^LRXN~Xo@4a1hMWF%y1hNGYODLT0skjM1u2?nKzIiWunf!Z3FpInYkYNW1Y&U

      client:
        # 监控服务器地址
        url: http://localhost:9000
        # 客户端实例配置
        instance:
          # 默认使用的是主机名注册，改为使用ip注册
          prefer-ip: true

  # 数据源配置
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url
    url: jdbc:mysql://localhost:3306/monolithic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    # 用户名
    username: root
    # 密码
    password: root
    # 指定使用的数据源
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池
    hikari:
      # 池中最大连接数（包括空闲和正在使用的连接）
      maximum-pool-size: 5
      # 池中最小空闲连接数量
      minimum-idle: 1

  data:
    # Redis服务器配置
    redis:
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # Redis数据库索引（默认为0）
      database: 0
      # 连接空闲超过N（s秒、ms毫秒，不加单位时使用毫秒）后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      timeout: 60s
      # Lettuce连接池配置
      lettuce:
        pool:
          # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为 (cpu * 2) + 2
          max-active: 10
          # 最大空闲连接数，默认8，推荐值：cpu * 2
          max-idle: 8
          # 最小空闲连接数，默认0
          min-idle: 0
          # 连接用完时，新的请求等待时间（s秒、ms毫秒），超过该时间抛出异常，默认-1（负值表示没有限制）
          max-wait: 5s

  redis:
    redisson:
      file: classpath:redisson-dev.yml

jwt:
  key: GkiYzIiLCJpc3MYjQzODLTQ1MWMtYjM1Ny1hMjMwZjE5M2JiOiJ4aWFuZ3FpYW4iLCJpYXQNkYy1hNGY0sInN1YiI6Ikp
  exp: 12h

# openapi文档配置
springdoc:
  api-docs:
    # 开启文档
    enabled: true

  swagger-ui:
    # 定义文档访问路径
    path: /swagger-ui.html
