server:
  port: ${MONOLITHIC_WEB_PORT:8080}
  servlet:
    context-path: /
    session:
      persistent: false

spring:
  # 数据源配置
  datasource:
    # 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url
    url: jdbc:mysql://localhost:3306/monolithic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    # 用户名
    username: root
    # 密码
    password: root
    # 指定使用的数据源
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池
    hikari:
      # 池中最大连接数（包括空闲和正在使用的连接）
      maximum-pool-size: 5
      # 池中最小空闲连接数量
      minimum-idle: 1

  data:
    # Redis配置
    redis:
      # 主机
      host: localhost
      # 端口
      port: 6379
      # 密码
      #password:
      # 数据库
      database: 0
      # 连接超时
      connect-timeout: 60s
      # 读超时
      timeout: 60s
      # Lettuce客户端配置
      lettuce:
        # 连接池配置
        pool:
          # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为 (cpu * 2) + 2
          max-active: 8
          # 最大空闲连接数，默认8，推荐值：cpu * 2
          max-idle: 8
          # 最小空闲连接数，默认0
          min-idle: 0
          # 从连接池获取连接，最多等待时间，超过该时间抛出异常，默认-1（表示没有限制）
          max-wait: 5s

  # Redis Redisson配置
  redis:
    redisson:
      file: classpath:redisson-dev.yml

#  # 邮件配置
#  # https://springdoc.cn/spring-boot/application-properties.html#appendix.application-properties.mail
#  mail:
#    # 邮件SMTP服务器地址，如：
#    # 1、smtp.qq.com
#    #   需要在QQ邮箱设置中开启 SMTP 服务，并且记得把配置文件中的 spring.mail.password 替换为你的 授权码。注意，不是 QQ 密码，关于 QQ 邮箱如何生成授权码你可以参阅 官方文档（https://service.mail.qq.com/detail/0/75）
#    # 2、smtp.163.com
#    #   【设置】->【POP3/SMTP/IMAP】->开启【POP3/SMTP服务】
#    host: ${MONOLITHIC_MONITOR_MAIL_HOST:smtp.example.com}
#    # 端口
#    port: ${MONOLITHIC_MONITOR_MAIL_PORT:25}
#    # 使用的协议
#    protocol: smtp
#    # 默认编码
#    default-encoding: UTF-8
#    # 用户名
#    username: ${MONOLITHIC_MONITOR_MAIL_USERNAME:your-email@example.com}
#    # 密码或授权码
#    password: ${MONOLITHIC_MONITOR_MAIL_PASSWORD:your-email-password}
#    # 发件人邮箱地址
#    from: ${spring.mail.username}
#    # 其他的属性
#    properties:
#      "mail.smtp.connectiontimeout": 5000
#      "mail.smtp.timeout": 3000
#      "mail.smtp.writetimeout": 5000
#      # 设置是否需要认证，如果为true,那么用户名和密码就必须的
#      # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的
#      "mail.smtp.auth": true
#      # STARTTLS 是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信
#      "mail.smtp.starttls.enable": true
#      "mail.smtp.starttls.required": true
#      "mail.smtp.ssl.enable": true
#      "mail.debug": true

# MinIO配置
minio:
  endpoint: http://localhost:9002
  access-key: m0dWHllxoipmIczh
  secret-key: Kr2Uq0tCHr0HjLLBHBiYzDs5tznle4jv

jwt:
  key: GkiYzIiLCJpc3MYjQzODLTQ1MWMtYjM1Ny1hMjMwZjE5M2JiOiJ4aWFuZ3FpYW4iLCJpYXQNkYy1hNGY0sInN1YiI6Ikp
  exp: 12h

# Actuator 配置
management:
  # 权限令牌
  token: kiiI6IkphFra!NUB4iLCJpYXQN^LRXN~Xo@4a1hMWF%y1hNGYODLT0skjM1u2?nKzIiWunf!Z3FpInYkYNW1Y&U

# openapi文档配置
springdoc:
  api-docs:
    # 开启文档
    enabled: true

  swagger-ui:
    # 定义文档访问路径
    path: /swagger-ui.html
