server:
  port: 8200
  servlet:
    context-path: /
    session:
      persistent: false

spring:
  data:
    # Redis配置
    redis:
      # 主机
      host: localhost
      # 端口
      port: 6379
      # 密码
      #password:
      # 数据库
      database: 0
      # 连接超时
      connect-timeout: 60s
      # 读超时
      timeout: 60s
      # Lettuce客户端配置
      lettuce:
        # 连接池配置
        pool:
          # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为 (cpu * 2) + 2
          max-active: 8
          # 最大空闲连接数，默认8，推荐值：cpu * 2
          max-idle: 8
          # 最小空闲连接数，默认0
          min-idle: 0
          # 从连接池获取连接，最多等待时间，超过该时间抛出异常，默认-1（表示没有限制）
          max-wait: 5s

  # Redis Redisson配置
  redis:
    redisson:
      file: classpath:redisson-dev.yml
